import PageIntro from '@/components/page-intro';
import CopyButton from '@/components/copy-button';
import { Monitor, Terminal, Laptop, Download } from 'lucide-react';
import releases from '../../releases-verified.json';
export const metadata = { title: 'Download v3.1.0' };
export default function Downloads() {
  const platforms = [
    { name: 'Windows', match: 'v3.1.0(Windows)', arch: 'Windows · x64', ext: '.exe', Icon: Monitor, instructions: 'Close the analyzer, run the installer, and follow the setup wizard. Launch from the Start menu.' },
    { name: 'Linux', match: 'v3.1.0(Linux)', arch: 'Debian / Ubuntu · amd64', ext: '.deb', Icon: Terminal, instructions: 'Install the package with apt, then launch e-callisto-fits-analyzer from your applications menu.' },
    { name: 'macOS', match: 'v3.1.0(MacOS)', arch: 'macOS 15 or later · Apple silicon arm64', ext: '.dmg', Icon: Laptop, instructions: 'Open the disk image and drag e-Callisto FITS Analyzer into Applications. This package is built for Apple silicon.' }
  ];
  return <><PageIntro label="DOWNLOAD THE ANALYZER · v3.1.0" title="One toolkit. A wider view of the Sun.">Process radio spectra, analyze solar images, and explore CME geometry. Choose your platform to get started.</PageIntro><section className="wrap content-section"><div className="cards">{platforms.map(p => { const r = releases.find(r => r.tag === p.match)!; const a = r.assets[0]; return <article className="card" key={p.name}><p.Icon className="platform-icon" size={30}/><h2>{p.name}</h2><p>{p.arch}</p><span className="tag">v3.1.0 · Latest release</span><a className="button primary" href={a.browser_download_url}><Download size={17}/>Download {p.ext}</a><p className="small" style={{marginTop:12}}>{(a.size/1e6).toFixed(1)} MB · Hosted on GitHub</p><p style={{marginTop:22}}>{p.instructions}</p><details style={{marginTop:20}}><summary className="small">SHA-256 checksum</summary><pre>{a.digest.replace('sha256:','')}</pre><CopyButton text={a.digest.replace('sha256:','')} label="Copy checksum"/></details><a className="text-link small" href={r.url}>Release notes</a></article>; })}</div>
    <div className="notice"><strong>New in v3.1.0</strong><p>Expanded radio analysis, ridge tracking, density-model comparisons, solar imaging, PFSS magnetic context, and GCS CME and shock reconstruction.</p><a className="text-link" href="/guide/introduction#what-is-new-in-version-3.1.0">Explore what’s new</a></div>
    <div className="prose"><h2>Install on Linux</h2><pre>sudo apt install ./e-callisto-fits-analyzer_3.1.0_amd64.deb</pre><p>If your graphics driver causes startup problems, try <code>CALLISTO_FORCE_SOFTWARE_OPENGL=1 e-callisto-fits-analyzer</code>.</p><h2>The complete v3.1.0 handbook</h2><p><a href="/guide">Read the web guide</a> or <a href="/guide/pdf">download the illustrated PDF</a> for installation, every workspace, measurement methods, formulas and troubleshooting.</p><p className="small">Package sizes and checksums are calculated from the supplied v3.1.0 installers.</p><p><a href="https://github.com/SaanDev/e-Callisto_FITS_Analyzer/releases">Browse all releases</a> for earlier versions.</p></div></section></>;
}
