import ToolMap from '@/components/tool-map';
import WorkspacePreview from '@/components/workspace-preview';
import SolarShowcase from '@/components/solar-showcase';
import { Download, Activity, Layers, ScanLine, BookOpen, Code2 } from 'lucide-react';
export default function Home() {
    return <>
    <section className="hero wrap"><a className="release-pill" href="/download">OPEN SCIENCE, OPEN POSSIBILITIES <span>v3.0.0 available</span></a><h1>A clearer view of<br /><em>our dynamic Sun.</em></h1><p className="hero-copy">From radio bursts to erupting coronal structures.<br className="desktop-break"/> Analyze e-CALLISTO spectra and solar images in one connected toolkit.</p><div className="actions"><a className="button primary" href="/download"><Download size={18}/> Download the analyzer</a><a className="button secondary" href="/guide"><BookOpen size={18}/> Explore the user guide</a></div><div className="hero-meta"><span>Windows</span><span>Linux</span><span>macOS</span><i />Free & open source</div><WorkspacePreview /></section>
    <div className="facts wrap"><div><strong>FITS, made accessible.</strong><span>Built for researchers and curious minds.</span></div><div><span className="eyebrow">OBSERVE</span><strong>Radio & imaging</strong></div><div><span className="eyebrow">UNDERSTAND</span><strong>Bursts & CMEs</strong></div><div><span className="eyebrow">REPRODUCE</span><strong>Shareable science</strong></div></div>
    <ToolMap /><section className="section wrap" id="radio-tool"><div className="section-heading"><div><span className="eyebrow">TOOL 01 · e-CALLISTO FITS ANALYZER</span><h2>Follow the signal.<br />Find the science.</h2></div><p>Process and analyze e-CALLISTO dynamic spectra, from the first FITS file to a publication-ready figure.</p></div><div className="feature-grid"><article className="feature"><Activity /><h3>Reveal the structure</h3><p>Subtract the background, tune display thresholds, and clean radio-frequency interference.</p></article><article className="feature"><ScanLine /><h3>Measure the burst</h3><p>Isolate features, extract intensity maxima, and investigate frequency drift and Type II band splitting.</p></article><article className="feature"><Layers /><h3>See the wider event</h3><p>Bring GOES X-rays, CME catalogs, and solar imagery into the context of your radio observations.</p></article></div></section>
    <SolarShowcase /><section className="learn-section"><div className="wrap learn-grid"><div><span className="eyebrow">START CURIOUS. GO DEEPER.</span><h2>Your next discovery<br />starts here.</h2><p>Exploring solar radio spectra, imaging an eruption, or refining an established workflow? Find your starting point.</p></div><div className="resource-links">{[['01', 'User guide', 'A practical tour of the analyzer.', '/guide'], ['02', 'Tutorials', 'Follow an observation from import to export.', '/tutorials'], ['03', 'The science', 'Understand the physics behind the spectrum.', '/science']].map(([n, title, body, url]) => <a href={url} key={n}><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div><BookOpen size={20}/></a>)}</div></div></section>
    <section className="section wrap community-banner"><div><span className="eyebrow">SCIENCE WORKS BETTER TOGETHER</span><h2>A shared sky.<br />A shared conversation.</h2><p>Ask questions, compare methods, and share what you’re learning with the community.</p><a className="button primary" href="/forum">Join the discussion</a></div><div className="citation-teaser"><span className="eyebrow">BUILT FOR RESEARCH</span><h3>Using the analyzer<br />in your work?</h3><p>Credit the software and make your methods easier to reproduce.</p><a className="text-link" href="/citation">Citation & BibTeX</a><a className="github-link" href="https://github.com/SaanDev/e-Callisto_FITS_Analyzer"><Code2 size={18}/> Explore the source on GitHub</a></div></section></>;
}
