import { Download, Activity, Layers, ScanLine, BookOpen, Code2, Radio } from 'lucide-react';
export default function Home() {
    return <>
    <section className="hero wrap"><a className="release-pill" href="/download">OPEN SCIENCE, OPEN POSSIBILITIES <span>v3.0.0 available</span></a><h1>A clearer view of<br />the <em>radio Sun.</em></h1><p className="hero-copy">Turn solar radio observations into scientific insight.<br className="desktop-break"/> Explore, process, and analyze e-CALLISTO FITS data in one workspace.</p><div className="actions"><a className="button primary" href="/download"><Download size={18}/> Download the analyzer</a><a className="button secondary" href="/guide"><BookOpen size={18}/> Explore the user guide</a></div><div className="hero-meta"><span>Windows</span><span>Linux</span><span>macOS</span><i />Free & open source</div><figure className="app-showcase"><div className="window-bar"><div className="window-dots"><i /><i /><i /></div><span>e-CALLISTO FITS Analyzer</span><span className="window-label">FROM OBSERVATION TO UNDERSTANDING</span></div><img src="/screenshots/noise_reduction.png" alt="Real e-CALLISTO FITS Analyzer screenshot: background-subtracted INDIA-GAURI radio spectrum, 20 December 2025"/><figcaption><Radio size={15}/> A real observation. A richer perspective. <span>INDIA-GAURI · 20 DEC 2025</span></figcaption></figure></section>
    <div className="facts wrap"><div><strong>FITS, made accessible.</strong><span>Built for researchers and curious minds.</span></div><div><span className="eyebrow">OBSERVE</span><strong>Dynamic spectra</strong></div><div><span className="eyebrow">UNDERSTAND</span><strong>Solar radio bursts</strong></div><div><span className="eyebrow">REPRODUCE</span><strong>Shareable science</strong></div></div>
    <section className="section wrap"><div className="section-heading"><div><span className="eyebrow">YOUR COMPLETE ANALYSIS WORKSPACE</span><h2>Follow the signal.<br />Find the science.</h2></div><p>From the first FITS file to a publication-ready figure, keep your analysis connected.</p></div><div className="feature-grid"><article className="feature"><Activity /><h3>Reveal the structure</h3><p>Subtract the background, tune display thresholds, and clean radio-frequency interference.</p></article><article className="feature"><ScanLine /><h3>Measure the burst</h3><p>Isolate features, extract intensity maxima, and investigate frequency drift and Type II band splitting.</p></article><article className="feature"><Layers /><h3>See the wider event</h3><p>Bring GOES X-rays, CME catalogs, and solar imagery into the context of your radio observations.</p></article></div></section>
    <section className="learn-section"><div className="wrap learn-grid"><div><span className="eyebrow">START CURIOUS. GO DEEPER.</span><h2>Your next discovery<br />starts here.</h2><p>New to solar radio astronomy or refining an established workflow? Find your starting point.</p></div><div className="resource-links">{[['01', 'User guide', 'A practical tour of the analyzer.', '/guide'], ['02', 'Tutorials', 'Follow an observation from import to export.', '/tutorials'], ['03', 'The science', 'Understand the physics behind the spectrum.', '/science']].map(([n, title, body, url]) => <a href={url} key={n}><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div><BookOpen size={20}/></a>)}</div></div></section>
    <section className="section wrap community-banner"><div><span className="eyebrow">SCIENCE WORKS BETTER TOGETHER</span><h2>A shared sky.<br />A shared conversation.</h2><p>Ask questions, compare methods, and share what you’re learning with the community.</p><a className="button primary" href="/forum">Join the discussion</a></div><div className="citation-teaser"><span className="eyebrow">BUILT FOR RESEARCH</span><h3>Using the analyzer<br />in your work?</h3><p>Credit the software and make your methods easier to reproduce.</p><a className="text-link" href="/citation">Citation & BibTeX</a><a className="github-link" href="https://github.com/SaanDev/e-Callisto_FITS_Analyzer"><Code2 size={18}/> Explore the source on GitHub</a></div></section></>;
}
